[[libhello]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "10a96c59ef5cadcd9d9687ea8703a00dc0ed06db"
os = "macos"

    [[libhello.download]]
    sha256 = "d110e9863ac7f9b22bde71cfbb113d8493c22d30edd8cb305259dff32f5e6d04"
    url = "https://github.com/terasakisatoshi/libhello_jll.jl/releases/download/libhello-v0.1.1+0/libhello.v0.1.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[libhello]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee377725cc88802e52f92957d03eb67aa21d5a04"
libc = "glibc"
os = "linux"

    [[libhello.download]]
    sha256 = "f99452793417e056ea81146271dceaf2526ae4cfd37c24cd386f919256bedbc8"
    url = "https://github.com/terasakisatoshi/libhello_jll.jl/releases/download/libhello-v0.1.1+0/libhello.v0.1.1.x86_64-linux-gnu-cxx11.tar.gz"
[[libhello]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a8d9b81d43439326a7e13aac87bf8052e9540095"
os = "windows"

    [[libhello.download]]
    sha256 = "8c84e7cdf84c69e36d43a14f976acb3f3d81195fde558596f20b95f93122571b"
    url = "https://github.com/terasakisatoshi/libhello_jll.jl/releases/download/libhello-v0.1.1+0/libhello.v0.1.1.x86_64-w64-mingw32-cxx11.tar.gz"
